stages:
  - lint
  - run
  - clean

lint:
  stage: lint
  tags: [gpu]
  image: bigbrother:latest
  script:
    - cd BigBrother 
    - uv sync
    - make lint
  rules:
    - when: always

run:
  stage: run
  tags: [gpu]
  image: bigbrother:latest
  script:
    - cd BigBrother && make docker_run
  rules:
    - when: always

clean:
  stage: clean
  tags: [gpu]
  script:
    - docker system prune -f
  rules:
    - when: always
