stages:
  - lint
  - run
  - clean

lint:
  stage: lint
  tags: [gpu]
  image: bigbrother:latest
  script:
    - cd BigBrother 
    - uv sync
    - make lint
  rules:
    - when: always

run:
  stage: run
  tags: [gpu]
  image: bigbrother:latest
  script:
    # Build Docker image without GPU for testing
    - cd BigBrother && make docker_run
  rules:
    - if: '$CI_COMMIT_TAG =~ /^run.*/'


clean:
  stage: clean
  tags: [gpu]
  script:
    - docker system prune -f
  rules:
    - when: always