default:
  image: nvidia/cuda:12.6.2-runtime-ubuntu24.04

stages:
  - setup
  - model

prepare_submodules:
  stage: setup
  script:
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.brandttech.dk" > ~/.git-credentials
    - nvidia-smi
  rules:
    - when: always

model:
  stage: model
  script:
    - BigBrother/run.sh
  tags:
    - gpu
