stages:
  - lint
  - run

lint:
  stage: lint
  tags: [gpu]
  image: bigbrother:latest
  script:
    - cd BigBrother && make lint
  rules:
    - when: always

run:
  stage: run
  tags: [gpu]
  image: bigbrother:latest
  script:
    # Build Docker image without GPU for testing
    - cd BigBrother && make docker_run
  rules:
    - when: always
