before_script:
  - cd BigBrother && docker build -f dockerfile -t bigbrother .

image: bigbrother:latest

stages:
  - setup
  - model

setup:
  stage: setup
  tags: [gpu]
  script:
    - apt-get update && apt-get install -y git nvidia-utils-535 && apt-get clean
  rules:
    - when: always

model:
  stage: model
  tags: [gpu]
  script:
    - cd /home/user/BigBrother && sh run.sh

