default:
  image: nvidia/cuda:12.6.2-runtime-ubuntu24.04

before_script:
  - git config --global credential.helper store
  - echo "https://oauth2:${MY_ACCESS_TOKEN}@gitlab.brandttech.dk" > ~/.git-credentials

stages:
  - model

model:
  stage: model
  script:
    - nvidia-smi
    - BigBrother/run.sh
  tags:
    - gpu
