stages:
  - lint
  - run

lint:
  stage: lint
  tags: [gpu]
  script:
    - cd BigBrother && make lint
  rules:
    - when: always

run:
  stage: run
  tags: [gpu]
  script:
    # Build Docker image without GPU for testing
    - cd BigBrother && docker build -f dockerfile -t bigbrother:latest .
    - docker images | grep bigbrother
    # Run without GPU temporarily to test basic functionality
    - docker run --rm bigbrother:latest
  rules:
    - when: always
