stages:
  - lint
  - run
  - clean
  - datagen

lint:
  stage: lint
  tags: [gpu]
  image: bigbrother:latest
  script:
    - cd BigBrother 
    - uv sync
    - make lint
  rules:
    - when: always

datagen:
  stage: datagen
  tags: [gpu]
  image: bigbrother:latest
  artifacts:
    untracked: false
    when: always
    access: all
    paths:
      - BigBrother/src/data/
    expire_in: "1 hrs"

run:
  stage: run
  tags: [gpu]
  image: bigbrother:latest
  script:
    - cd BigBrother && make docker_run
  rules:
    - when: always
  artifacts:
    untracked: false
    when: always
    access: all
    paths:
      - BigBrother/results/
    expire_in: "4 mos"

clean:
  stage: clean
  tags: [gpu]
  script:
    - docker system prune -f
  rules:
    - when: always
