stages:
  - lint
  - run

lint:
  stage: lint
  tags: [gpu]
  script:
    - cd BigBrother && make lint
  rules:
    - when: always

run:
  stage: run
  tags: [gpu]
  script:
    # Build and run using Makefile target
    - cd BigBrother && make docker_run
  rules:
    - when: always
