variables:
  GIT_CREDENTIALS: "oauth2:${GIT_AUTH_TOKEN}"

before_script:
  - git config --global credential.helper store
  - echo "https://${GIT_CREDENTIALS}@gitlab.brandttech.dk" > ~/.git-credentials

model:
  script:
    - BigBrother/run.sh
  tags:
    - gpu