image: nvidia/cuda:12.6.2-runtime-ubuntu24.04

stages:
  - setup
  - model

setup:
  stage: setup
  tags: [gpu]
  script:
    - apt-get update && apt-get install -y git nvidia-utils-535 && apt-get clean
    - nvidia-smi
  rules:
    - when: always

model:
  stage: model
  tags: [gpu]
  script:
    - BigBrother/run.sh

